# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rodolfo Probst
email: probstrodolfo [at] gmail.com
description: I am a Postdoctoral Fellow at the Science Research Initiative program interested in phylogenetics, symbioses, insects, and science communication.
twitter_username: probstrodolfo
github_username: probstrodolfo
minimal_mistakes_skin: sunset
search: false

# Build settings
layout: single
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 2 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Rodolfo Probst"
  avatar : "/assets/images/Headshot_Probst-Rodolfo.jpg"
  bio    : "Evolutionary biologist and entomologist."
  links:
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-5885-5701"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.com.au/citations?user=S8om22EAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/probstrodolfo"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/probstrodolfo"
    
   
#footer:
   # - label: "ORCID"
    #  icon: "fab fa-fw fa-orcid"
     # url: "https://orcid.org/0000-0002-5885-5701"
   # - label: "Google Scholar"
    #  icon: "fab fa-fw fa-google-scholar"
     # url: "https://scholar.google.com.au/citations?user=S8om22EAAAAJ&hl=en"
   # - label: "GitHub"
    #  icon: "fab fa-fw fa-github"
     # url: "https://github.com/probstrodolfo"
      
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
